###
# Post Register

POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "name":"Adam-19",
    "email":"adam-19@yahoo.ca",
    "password":"123456"
}

###
# Login 

POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email":"adam-19@yahoo.ca",
    "password":"123456"
}

###
# Post a new post 

POST  http://localhost:5000/api/users/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVkY2NiMDI3MjU2ZjliMWZiYzdmYTI2YyIsIm5hbWUiOiJBZGFtLTE5IiwiZW1haWwiOiJhZGFtLTE5QHlhaG9vLmNhIiwicGFzc3dvcmQiOiIkMmEkMTAkRmg1dC9sV2QzTGM3dzNMekVwUDZBdUpQNFpIVEVhNTdsVThQaUhJNGt0OUQ1c3dOSG85VWUiLCJkYXRlQ3JlYXRlZCI6IjIwMTktMTEtMTRUMDE6Mzg6NDcuMDE0WiIsIl9fdiI6MH0sImlhdCI6MTU3MzY5NTU0MSwiZXhwIjoxNTczNjk1NjI3fQ.9yIyi-2mHfnarRKBmyHXU-DhYXgC_y6jQGG0IcmguO0